# Site settings
title: flyingrub
header-img: img/home-bg.jpg
email: flyinggrub@gmail.com
description: "A minimalist's blog"
baseurl: ""
url: "http://flyingrub.github.io"
twitter_username: burgniylf
github_username: flyingrub
soundcloud_username: flyingrub

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
